
version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: math_game
      MYSQL_USER: mguser
      MYSQL_PASSWORD: mgpass
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: math_game
      DB_USER: mguser
      DB_PASS: mgpass
      PORT: 5000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"

volumes:
  db_data:
